---
- name: install java dependencies
  package: >
    name={{ item }}
    state=latest
  with_items:
    - java-1.8.0-openjdk-headless
    - http://repo.rundeck.org/latest.rpm 
    - rundeck
    - rundeck-config
    - libselinux-python

- name: fix grails_serverurl
  lineinfile: >
    regexp="grails.serverURL"
    line=grails.serverURL=http://rundeck.{{ldap.domain}}:4440
    state=present
    dest=/etc/rundeck/rundeck-config.properties

- name: get ansible plugin 
  get_url: > 
    url=https://github.com/Batix/rundeck-ansible-plugin/releases/download/1.3.2/ansible-plugin-1.3.2.jar
    dest=/var/lib/rundeck/libext/ansible-plugin-1.3.2.jar
    mode=0775

- name: get ec2 plugin 
  get_url: > 
    url=https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin/releases/download/v1.5.2/rundeck-ec2-nodes-plugin-1.5.2.jar
    dest=/var/lib/rundeck/libext/rundeck-ec2-nodes-plugin-1.5.2.jar
    mode=0775

- name: add jaas-ldap.conf
  template: >
    src=jaas-ldap.conf.j2
    dest=/etc/rundeck/jaas-ldap.conf

- name: restart rundeckd
  service: >
    name=rundeckd
    state=restarted
